CREATE TABLE towns (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(45) NOT NULL
);

CREATE TABLE stadiums (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(45) NOT NULL,
	capacity INT NOT NULL CHECK(capacity > 0),
	town_id INT NOT NULL REFERENCES towns(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE teams (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(45) NOT NULL,
	established DATE NOT NULL,
	fan_base INT NOT NULL CHECK (fan_base >= 0) DEFAULT 0,
	stadium_id  INT NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE coaches (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(10) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	salary NUMERIC(10, 2) NOT NULL CHECK(salary >= 0) DEFAULT 0,
	coach_level INT NOT NULL CHECK(coach_level >= 0) DEFAULT 0
);

CREATE TABLE skills_data (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	dribbling INT CHECK(dribbling >= 0) DEFAULT 0,
	pace INT CHECK(pace >= 0) DEFAULT 0,
	"passing" INT CHECK(passing >= 0) DEFAULT 0,
	shooting INT CHECK(shooting >= 0) DEFAULT 0,
	speed INT CHECK(speed >= 0) DEFAULT 0,
	strength INT CHECK(strength >= 0) DEFAULT 0
);

CREATE TABLE players (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(10) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	age INT NOT NULL CHECK(age >= 0) DEFAULT 0,
	"position" CHAR(1) NOT NULL,
	salary NUMERIC(10, 2) NOT NULL CHECK(salary >= 0) DEFAULT 0,
	hire_date TIMESTAMP,
	skills_data_id INT NOT NULL REFERENCES skills_data(id) ON DELETE CASCADE ON UPDATE CASCADE,
	team_id INT REFERENCES teams(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE players_coaches (
	player_id  INT REFERENCES players(id) ON DELETE CASCADE ON UPDATE CASCADE,
	coach_id  INT REFERENCES coaches(id) ON DELETE CASCADE ON UPDATE CASCADE
);







